spring:
  application:
    name: dd-user
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.113.96:8848
        naming:
          log:
            level: warn
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error

