spring:
  application:
    name: dd-lighting
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.96:8848
        naming:
          log:
            level: warn
